# Generated by Django 2.2.7 on 2019-11-22 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名字')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名字')),
            ],
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('url', models.URLField(blank=True, verbose_name='文章封面URL')),
                ('desc', models.TextField(blank=True, verbose_name='简介文章的desc')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Category', verbose_name='文章所属分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='blog.Tag', verbose_name='文章标签')),
            ],
        ),
    ]
