# Generated by Django 2.2.7 on 2019-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='文章封面URL'),
        ),
    ]
