# Generated by Django 2.2.7 on 2019-11-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191122_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='ok', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='blog.Category', verbose_name='文章所属分类'),
        ),
    ]
