# Generated by Django 2.2.7 on 2019-11-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191123_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='ok', on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='blog.Category', verbose_name='文章所属分类'),
        ),
    ]
